### ISSUE TITLE
HTML appender docs

### ISSUE THREAD

**Issue by tgalery** [diegoceccarelli/dexter-eval#1]
Hi Diego, this is more of a question, but I was wondering if there are any docs on how to produce the html for the evaluations. Also, it seems that dev is quite ahead of master, would it be better to use dev as the base branch ?

**Comment by diegoceccarelli** [comment]
hei @tgalery, 
the HTML was a quick hack that I wrote when I was doing the microsoft ERD track, never had time to clean so I prefered not to publish in the main branch. Once than I'll start pimping the new version of dexter I'll probably clean and use it (gerbil seems to big for my needs). 
If you go in the develop branch (and create the jar using mvn assembly:assembly). There are two types of html output: 

## unique html file

all the documents evaluated in one unique html file  (just append a .html at the end of the command line) 

```
 ./scripts/evaluate.sh example/wikiminer-iitb-predictions.json.gz example/iitb-dataset.json.gz Me example/conf-macro-measures.txt output.html 
```

## eval folder

A directory with one html file per document ( append a string ending with ".eval" at the of the command line, it will create a directory) 

```
./scripts/evaluate.sh example/wikiminer-iitb-predictions.json.gz example/iitb-dataset.json.gz Me example/conf-macro-measures.txt output.eval 
```

**Comment by tgalery** [comment]
Cheers @diegoceccarelli ! I will do the first one! I'm closing this issue then!
